title: Transaction Monitoring Portfolio
description: >
  Portfolio project analyzing rule-based suspicious transaction “indicators,”
  deduplicating alerts and visualizing overlaps with Python, pandas and Plotly.
baseurl: "/transaction-indicator-analytics"
url: "https://marcin-charzynski.github.io"
collections:
  pages:
    output: true
    permalink: /:path/
plugins:
  - jekyll-remote-theme
  - jekyll-ipynb
remote_theme: Marcin-Charzynski/marcin-charzynski.github.io
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    line_numbers: true
